<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a410a0a746573742e70726f746f12046b6a637822250a0a68656c6c6f77" .
            "6f726c64120a0a026964180120012805120b0a0373747218022001280962" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

